### ISSUE TITLE
Host style guide on public domain

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/style-guide-guide#1]
Upload current style guide for stakeholder review.

Current style guide: http://template.library.emory.edu/styleguide/

 - [x] Develop deployment process
 - [x] Deploy to template.library.emory.edu/styleguide/

**Comment by kristianserrano** [comment]
For editing content, https://stackedit.io/

**Comment by laurenhamel** [comment]
Also found this MS Word plugin: http://www.writage.com/

**Comment by laurenhamel** [comment]
I put in the deployment process and went ahead and deployed the current style guide (mostly placeholder content) to the URL in the description. I also uploaded the current version of the Sass Framework's [SassDocs](http://template.library.emory.edu/styleguide/sassdocs/current) along with it. Let me know if you run into any issues.
